#!/bin/sh

# Run tests
npm run test
if [ $? -ne 0 ]; then
    echo "Tests failed! Push aborted."
    exit 1
fi

# Run lint
npm run lint --fix
if [ $? -ne 0 ]; then
    echo "Linting failed! Push aborted."
    exit 1
fi

# If everything passes, allow the push to proceed
exit 0
